name: lotto_defence_tools
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  json_annotation: ^3.0.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  json_serializable: ^3.2.2
  pedantic: ^1.8.0
  sass_builder: ^2.1.3
  test: ^1.6.0
