const ARTIFACT_CRIT_CHANCE = 20;
const FLOWER_ATTACK_DAMAGE = 1.2;
const FLOWER_ATTACK_SPEED = 1.15 * 1.25;
const FLOWER_DAMAGE_TAKEN = 1.1;

const BLESS_DAMAGE = 20;

const SPEC_OPS_NOVA_ATTACK_SPEED = 15;
const TERRA_TRON_CRIT_CHANCE = 10;
const AMON_ATTACK_DAMAGE = 30;
const SPEAR_OF_ADUN_CRIT_DAMAGE = 30;
const XELNAGA_KERRIGAN_CRIT_CHANCE = 10;

const DT_SPEED = 1.15;

const UNIT_LEVEL_ATTACK_DAMAGE_MODIFIER = 5;
const SINGLE_UNIT_ATTACK_DAMAGE = 30;
const DUPLICATE_UNIT_ATTACK_DAMAGE_PENALTY = 10;

const STARTER_GEM_STATS = 5;
const STARTER_GEM_MULTIPLIER = 2;
const STARTER_GEM_EXPERIENCE = 20000;

const POWER_BANKER_GEM_STATS = 50;

// Source: http://www.arcade.sc/threads/12002-QUESTION-Multi-Critical?p=38213#post38213
const MULTI_CRIT_CHANCE = 1 / 3;
const MULTI_CRIT_DAMAGE = 3 / 4;

const BASE_MULTI_HIT_CHANCE = 20;

const GENERAL_BONUS_SP = 2000;
const STARTING_SP = 5000;
